### PR TITLE
Compilation: support backslashes in filenames when ms-extensions are enabled

### PR DESCRIPTION
**Pull request by Vexu**
Ticks a box in #509

### CODE REVIEW

**Comment by squeek502** [comment]
This seems to lead to an infinite loop if the `#include` file is not found.

```
// test.c
#include "missing.h"
```

```
> arocc -E test.c
.\test.c:1:10: fatal error: 'missing.h' not found
#include "missing.h"
          ^
```

```
> arocc -E --emulate=msvc test.c
```
(never terminates)

**Comment by Vexu** [comment]
Should work now.

**Comment by squeek502** [comment]
Note that `\` in an include path still fails at the parsing stage on this branch. Example:

```
.\VCExplore.Rc:492:10: error: expected "FILENAME" or <FILENAME>
#include "res\VCExplore.rc2"  // non-Microsoft Visual C++ edited resources
         ^
.\VCExplore.Rc:492:15: error: extra tokens at end of macro directive
#include "res\VCExplore.rc2"  // non-Microsoft Visual C++ edited resources
              ^
```

**Comment by squeek502** [comment]
Looking good, new `win32-samples-rc-tests` results for this branch:

```
33 .rc files processed with discrepancies
different .res outputs:     0
unexpected compile errors:  33
missing compile errors:     0

452 .rc files processed without discrepancies
identical .res outputs:     427
expected compile errors:    25
```

up from (https://github.com/Vexu/arocc/pull/511#issuecomment-1741054791):

```
57 .rc files processed with discrepancies
different .res outputs:     0
unexpected compile errors:  57
missing compile errors:     0

428 .rc files processed without discrepancies
identical .res outputs:     403
expected compile errors:    25
```

**Comment by squeek502** [comment]
Only 29 files left that have unexpected results:

```
29 .rc files processed with discrepancies
different .res outputs:     0
unexpected compile errors:  29
missing compile errors:     0

456 .rc files processed without discrepancies
identical .res outputs:     431
expected compile errors:    25
```

All the remaining files should be fixed by `#line` directives.

**Pull request merged**
