### PR TITLE
Build: Add a build.zig.zon file

### PR DESCRIPTION
**Pull request by ehaas**
Not sure how to handle the `version` field - we also compute it in build.zig

### CODE REVIEW

**Review by Vexu — APPROVED** [review]
> Not sure how to handle the version field - we also compute it in build.zig

I guess it should only be updated on tagged releases? Either way we can consider the version reported by the executable more accurate.

**Comment by ehaas** [comment]
This is more of a Zig build system question, but my I was also wondering about the `include` directory - if someone is consuming `aro` as a package, is there any way to programmatically access that directory?

**Comment by Vexu** [comment]
I'm guessing something like `b.dependency("aro").path("include/stddef.h")` should work?

**Comment by ehaas** [comment]
That worked! I'll put together a quick README entry / example for using aro as a dependency.

**Pull request merged**
