### PR TITLE
Parser: add support for statement expressions

### LINKED ISSUE #171: Add statement expression support
A statement expression is a compound statement enclosed in parentheses. The value of the statement expression is the value of the last semicolon-terminated expression within the compound statement.

Simple example
```c
int foo(void) {
    int y = ({
        int x = 5;
        x++;
        x - 5;
    });
    return y;
}
```
(This would return `1`)

See full description: https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

In clang this construct is available in all language standards

### PR DESCRIPTION
**Pull request by ehaas**
Closes #171

### CODE REVIEW

**Comment by ehaas** [comment]
There are (at least) two issues currently:

1. How to handle unused expressions - if a statement expression is unused, clang warns by pointing to the last statement in the statement expression and says that it's unused. `maybeWarnUnused` has no way of knowing if the result is the last statement in a statement expression, as far as I can tell. One idea I had was that it could push append to an ArrayList if currently parsing a statement expression, and then clean things up after the full statement expression had been parsed.
2. If a statement expression is used as an initializer, the statement expression is allowed to refer to the variable it's initializing. I didn't see any non-invasive ways to support this, since it seems like we need a declref to a node that doesn't exist yet.

**Comment by Vexu** [comment]
>1. How to handle unused expressions 

I would solve this by adding another parameter to `compoundStmt`:
```zig
stmt_expr_state: ?*struct {
    last_expr_loc: TokenIndex,
    last_expr_res: Result,
},
```
Then just tweak the mechanism for unused value error a bit. This would also help get rid of `compoundStmtLastNode`.
 
>2. If a statement expression is used as an initializer, the statement expression is allowed to refer to the variable it's initializing. I didn't see any non-invasive ways to support this, since it seems like we need a declref to a node that doesn't exist yet.

`decl_ref` currently doesn't need the variable to have any node so this shouldn't be an issue as long as you can limit the visibility to inside the statement expression.

**Comment by ehaas** [comment]
I might be missing something obvious, but I'm not sure how to get the `unused result` warning to point to the relevant expression. My current strategy is to unconditionally remove the `unused result` warning for the final expression in a statement expression, since it might actually be used. The problem is that `maybeWarnUnused` gets the `expr_start` of the whole statement expression. In theory it would be possible to get the location of the final expression but it seems like it would be really messy.

The alternative would be to *not* unconditionally remove the unused result warning; but then we would need to remove it later and I think we're back at the same place of needing to figure out the location of the final expression (since we wouldn't want to remove an unused result warning pointing to an earlier expression in the stmt expr.

**Comment by Vexu** [comment]
> I might be missing something obvious, but I'm not sure how to get the `unused result` warning to point to the relevant expression.

I don't think it is possible in any reasonable way currently but once we start attaching a source token to the nodes in some way we should be able to get much closer.

**Pull request merged**
